language: generic
sudo: required
os:
  - linux
  - osx
notifications:
  email: false
script:
  - git config --global user.name "Test name"
  - git config --global user.email "test@localhost"
  - ./setup
