language: generic
sudo: required
python:
  - 2.7
os:
  - linux
  - osx
# matrix:
#   include:
#     - os: linux
#       dist: trusty
#       sudo: required
#       python: "3.4"
#       install: pip install ansible
#     - os: osx
notifications:
  email: false
install: sudo pip install git+git://github.com/ansible/ansible.git@devel
script: ./setup
