- hosts: localhost
  vars:
    - node_version: 7
    - is_osx: ansible_os_family == 'Darwin'

  tasks:
    # essentials:
    #- include: tasks/homebrew.yml
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml

    #
    # specific stuff than can be commented out
    #
    # editors, IDEs, terminals, etc
    #- include: tasks/intellij.yml
    #- include: tasks/terminal.yml

    # browsers
    #- include: tasks/chrome.yml
    #- include: tasks/vivaldi.yml
    #- inlcude: tasks/firefox.yml

    # database
    - include: tasks/mysql.yml
    - include: tasks/redis.yml

    # tools
    #- include: tasks/docker.yml
    - include: tasks/ngrok.yml

    # languages
    - include: tasks/java.yml
    - include: tasks/node.yml

    # chat
    - include: tasks/skype.yml
    #- include: tasks/slack.yml
    #- include: tasks/telegram.yml

    # media
    - include: tasks/vlc.yml
