- hosts: localhost
  roles:
    # -
  vars:
    - node_version: 6
    - is_travis: ansible_env.TRAVIS_JOB_ID is not defined
  tasks:
    # essentials:
    - include: tasks/apt.yml
      when: ansible_os_family == 'Debian'
    - include: tasks/homebrew.yml
      when: ansible_os_family == 'Darwin'
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml

    # specific stuff than can be commented out:
    - include: tasks/atom.yml
    - include: tasks/chrome.yml
    - include: tasks/diffmerge.yml
    - include: tasks/docker.yml
    - include: tasks/golang.yml
    - include: tasks/java.yml
    - include: tasks/node.yml
    - include: tasks/postgres.yml
    - include: tasks/python.yml
    - include: tasks/quicklook.yml
      when: ansible_os_family == 'Darwin'
    - include: tasks/ruby.yml
    - include: tasks/skype.yml
    - include: tasks/slack.yml
    - include: tasks/slate.yml
      when: ansible_os_family == 'Darwin'
    - include: tasks/spotify.yml
    - include: tasks/sublime-text.yml
    - include: tasks/telegram.yml
    - include: tasks/terminal.yml
    - include: tasks/vlc.yml
    - include: tasks/vpn.yml

    # TODO: dbeaver, intellij, eclipse, vlc, fonts?, maven 3.2?,
    # dropbox
