- hosts: localhost
  become: false
  connection: local
  roles:
    # -
  tasks:
    # essentials:
    - include: tasks/homebrew.yml
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml

    # specific stuff than can be commented out:
    - include: tasks/terminal.yml
    - include: tasks/chrome.yml
    - include: tasks/telegram.yml
    - include: tasks/spotify.yml
    - include: tasks/java.yml
    - include: tasks/vpn.yml
    - include: tasks/quicklook.yml
