# TODO: simplify this once ansible 2.1 is out
- name: Add Atom PPA
  apt_repository: repo='ppa:webupd8team/atom'
  when: ansible_os_family == 'Debian'
- name: Install Atom
  package: name=atom
  when: ansible_os_family == 'Debian'

- name: Install Atom
  homebrew_cask: name=atom
  when: is_osx
