# TODO: simplify this once ansible 2.1 is out
- name: Download atom
  get_url: url='https://atom.io/download/deb' dest=/tmp/atom.deb
  when: ansible_os_family == 'Debian'
- name: Install Atom
  apt: deb=/tmp/atom.deb
  when: ansible_os_family == 'Debian'

- name: Install Atom
  homebrew_cask: name=atom
  when: ansible_os_family == 'Darwin'
