- name: Check if atom is installed
  command: dpkg-query -W atom
  register: atom_check
  failed_when: atom_check.rc > 1
  changed_when: atom_check.rc == 1
  when: ansible_os_family == 'Debian'
- name: Download atom
  get_url: url="https://atom.io/download/deb" dest="/tmp/atom.deb"
  when: ansible_os_family == 'Debian' && atom_check.rc == 1
- name: Install Atom
  apt: deb=/tmp/atom.deb
  when: ansible_os_family == 'Debian' && atom_check.rc == 1

- name: Install Atom
  homebrew_cask: name=atom
  when: ansible_os_family == 'Darwin'
