# TODO: simplify this once ansible 2.1 is out
- name: Download atom
  command: curl -o /tmp/atom.deb https://atom.io/download/deb
  when: ansible_os_family == 'Debian'
- name: Install Atom
  apt: deb=/tmp/atom.deb
  when: ansible_os_family == 'Debian'

- name: Install Atom
  homebrew_cask: name=atom
  when: ansible_os_family == 'Darwin'
