- name: Install Ubuntu-only core packages
  package: name={{item}}
  with_items:
    - openssh-server
    - smbclient
    - ubuntu-restricted-extras
    - xsel
  when: ansible_distribution == 'Ubuntu'

- name: Install OSX-only core packages
  package: name={{item}}
  with_items:
    - coreutils
    - findutils
    - gawk
    - gnu-getopt
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnutls
    - grc
    - unrar
  when: ansible_os_family == 'Darwin'

- name: Install core packages
  package: name={{item}}
  with_items:
    - curl
    - git
    - htop
    - vim
    - wget
    - zsh
