- name: Download dotfiles
  git: repo=https://github.com/caarlos0/dotfiles.git dest=~/.dotfiles update=yes version=ansible
  become: false
- name: Setup dotfiles
  shell: cd ~/.dotfiles && ./script/bootstrap
  become: false
- name: Set zsh as default shell
  shell: chsh -s /bin/zsh
  become: false
