- name: Download dotfiles
  git: repo=https://github.com/caarlos0/dotfiles.git dest=~/.dotfiles update=yes version=ansible
- name: Install antibody
  shell: curl -s https://raw.githubusercontent.com/getantibody/installer/master/install | bash -s
  when: ansible_distribution == 'Ubuntu'
- name: Install antibody
  homebrew: antibody
  when: ansible_os_family == 'Darwin'
- name: Setup dotfiles
  shell: cd ~/.dotfiles && ./script/bootstrap
- name: Set zsh as default shell
  shell: chsh -s $(which zsh)
