- name: Download dotfiles
  git: repo=https://github.com/caarlos0/dotfiles.git dest=~/.dotfiles update=yes version=ansible
- name: Setup dotfiles
  shell: cd ~/.dotfiles && ./script/bootstrap
- name: Set zsh as default shell
  shell: chsh -s $(which zsh)
