- name: Install Jenv
  package: name=jenv

- name: Install OpenJDK  8, latest
  homebrew_cask: name={{ item }}
  when: is_osx
  with_items:
    - adoptopenjdk
    - adoptopenjdk8

- name: "Get available JDKs"
  shell: "ls /Library/Java/JavaVirtualMachines/"
  register: jvms
  ignore_errors: yes
  changed_when: False

- name: "Register JDKs"
  shell: "jenv add /Library/Java/JavaVirtualMachines/{{ item }}/Contents/Home || true"
  with_items: jvms.stdout_lines
  ignore_errors: yes
  register: result
  changed_when: "'already' not in result.stdout"

- name: "Installs shims for all JDKs"
  shell: "jenv rehash"
  changed_when: False

- name: Install maven
  package: name=maven
  become: false
