- name: Install Java
  homebrew_cask: name={{item}} state=present
  with_items:
    - java
    - java7
  when: ansible_os_family == 'Darwin'
- name: Add Java repository
  apt_repository: repo='ppa:webupd8team/java'
  when: ansible_distribution == 'Ubuntu'
- name: Accept Java's License
  command: echo {{item}} shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  with_items:
    - oracle-java7-installer
    - oracle-java8-installer
  when: ansible_distribution == 'Ubuntu'
- name: Install Java
  package: name={{item}} state=present
  with_items:
    - oracle-java7-installer
    - oracle-java8-installer
  when: ansible_distribution == 'Ubuntu'
- name: Install Maven and Gradle
  package: name={{item}} state=present
  with_items:
    - maven
    - gradle
