- name: Install PostgresApp
  homebrew_cask: postgres
  when: ansible_os_family == 'Darwin'

- name: Install PostgreSQL
  package: name={{item}}
  with_items:
    - postgresql
    - postgresql-contrib
  when: ansible_distribution == 'Ubuntu'
- name: Setup pg_hba
  copy: src=pg_hba.conf dest={{ lookup('pipe', 'ls /etc/postgresql/9.*/main/pg_hba.conf') }} mode=0750
  when: ansible_distribution == 'Ubuntu'
- name: Setup postgresql.conf
  lineinfile: dest={{ lookup('pipe', 'ls /etc/postgresql/9.*/main/postgresql.conf') }} line="listen_addresses = '*'"
  when: ansible_distribution == 'Ubuntu'
