- name: Add SublimeText repository
  apt_repository: repo='ppa:webupd8team/sublime-text-3'
  when: ansible_distribution == 'Ubuntu'
- name: Install SublimeText
  package: name=sublime-text-installer
  when: ansible_distribution == 'Ubuntu'

- name: Install SublimeText
  homebrew_cask: name=sublime-text3
  when: ansible_os_family == 'Darwin'
