- name: Add SublimeText repository
  apt_repository: repo='ppa:webupd8team/sublime-text-3'
  when: is_ubuntu
- name: Install SublimeText
  package: name=sublime-text-installer
  when: is_ubuntu

- name: Install SublimeText
  homebrew_cask: name=sublime-text3
  when: is_osx
